cc_binary(
    name = "rope_user",
    srcs = ["rope_user.cpp"],
    deps = [
        ":rope",
    ],
)

cc_library(
    name = "rope",
    srcs = ["rope.cpp"],
    hdrs = ["rope.h"],
    deps = [],
)

cc_binary(
    name = "node_user",
    srcs = ["node_user.cpp"],
    deps = [
        ":node",
    ],
)

cc_library(
    name = "node",
    srcs = ["node.cpp"],
    hdrs = ["node.h"],
    deps = [],
)
